import { Nav } from "@/components";
import { Main } from "@/containers";
import { DataType, hotList, popularList } from "@/contents/data";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>숏다리</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main popularList={popularList} hotList={hotList} />
      </main>
      <footer>
        <Nav />
      </footer>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const popularData: DataType[] = await popularList;
    const hotData: DataType[] = await hotList;
    return {
      props: {
        popularList: popularData,
        hotList: hotData,
      },
    };
  } catch (err) {
    console.log(err);
  }
}
