import { Nav } from "@/components";
import { Main } from "@/containers";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>숏츠</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main />
      </main>
      <footer>
        <Nav />
      </footer>
    </>
  );
}
